<!DOCTYPE html>
<html lang="ro">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Print QR Codes - FleetLog</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            @page {
                size: A4;
                margin: 1cm;
            }
            body {
                print-color-adjust: exact;
                -webkit-print-color-adjust: exact;
            }
            .no-print {
                display: none !important;
            }
            .qr-grid {
                display: grid !important;
                grid-template-columns: repeat(3, 1fr) !important;
                gap: 1.5rem !important;
            }
            /* Avoid breaking a QR code between pages */
            .qr-item {
                break-inside: avoid;
                page-break-inside: avoid;
            }
        }

        .qr-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
            gap: 2rem;
        }
    </style>
</head>
<body class="bg-slate-50 font-sans p-8">
    <div class="max-w-4xl mx-auto">
        <div class="no-print mb-8 flex justify-between items-center bg-white p-6 rounded-2xl shadow-sm border border-slate-200">
            <div>
                <h1 class="text-2xl font-bold text-slate-800">Print QR Codes</h1>
                <p class="text-slate-500">Listă automată cu codurile QR pentru toată flota (Active).</p>
            </div>
            <div class="flex space-x-3">
                <button onclick="window.print()" class="bg-blue-600 text-white px-6 py-2 rounded-xl font-bold hover:bg-blue-700 shadow-md transition-all flex items-center">
                    <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path></svg>
                    Print Now
                </button>
                <button onclick="window.close()" class="bg-slate-100 text-slate-600 px-6 py-2 rounded-xl font-bold hover:bg-slate-200 transition-all">
                    Close
                </button>
            </div>
        </div>

        <div class="qr-grid bg-white p-8 rounded-2xl border border-slate-200 shadow-inner">
            <?php foreach ($vehicles as $vehicle): ?>
                <?php 
                    $qrUrl = "/qr/generate?sf=10&d=" . urlencode("https://" . ($_SERVER['HTTP_HOST'] ?? 'fleet.daserdesign.ro') . "/driver/start-trip?qr=" . $vehicle['qr_code']);
                ?>
                <div class="qr-item flex flex-col items-center justify-center p-6 border-2 border-slate-100 rounded-2xl transition hover:border-blue-200 bg-white">
                    <div class="mb-4">
                        <img src="<?php echo $qrUrl; ?>" alt="QR <?php echo $vehicle['license_plate']; ?>" class="w-32 h-32">
                    </div>
                    <div class="text-center">
                        <div class="text-xs text-slate-400 font-bold uppercase tracking-wider mb-1"><?php echo htmlspecialchars($vehicle['make'] . ' ' . $vehicle['model']); ?></div>
                        <div class="text-xl font-black text-slate-800 font-mono ring-1 ring-slate-200 bg-slate-50 px-3 py-1 rounded-lg inline-block">
                            <?php echo htmlspecialchars($vehicle['license_plate']); ?>
                        </div>
                    </div>
                    <div class="mt-2 text-[10px] text-slate-300 font-mono">
                        SCAN TO START TRIP
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <?php if (empty($vehicles)): ?>
            <div class="text-center py-20 bg-white rounded-2xl border border-dashed border-slate-300">
                <p class="text-slate-500 italic text-lg">Nu există mașini active în flotă.</p>
            </div>
        <?php endif; ?>

        <div class="mt-12 text-center text-slate-400 text-xs no-print">
            Generated by FleetLog Automation &bull; <?php echo date('d.m.Y H:i'); ?>
        </div>
    </div>
</body>
</html>
